### ISSUE TITLE
VueX Store as content Source

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#10]
- [x] Landing
- [x] Intro
- [x] Recap
- [x] Sponsor
- [x] Speakers Tile
- [ ] Past Events
- [x] Footer

**Comment by Humeira** [comment]
@MrSunshyne anyone working on this atm?

cc @cedpoilly

**Comment by MrSunshyne** [comment]
The following will be in the Vue template files directly : 
- Landing
- Intro
- Recap
- Footer

The following is from sessionize API :
- Spekaer Tile (Done)

The following from Spreadsheet : 
- Sponsor (Done)

We don't have a look and feel for the past events page yet. (Pending)
