### ISSUE TITLE
Efficient Background 

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#14]
The background looks quite hefty (in terms of file size). However, there might be ways to make it smaller by simplifying the texture and converting it to SVG. 

The idea is to break the texture to different layers, convert the to SVG, the assemble them again as multiple background image layers in the multiple components so that they play nicely together even when the page is resized.

Illustrators in the community? Join the crew !

**Comment by MrSunshyne** [comment]
hi @takachou. There's no background on the website for now. See [staging](https://youthful-panini-25fb9a.netlify.com/#/)

There's a link to the PSDs in the contributing guide [here](https://github.com/mscraftsman/devcon2019/blob/dev/CONTRIBUTING.md) under the design section

**Comment by takachou** [comment]
i got the psd, indeed at first try i got everything deconstructed but still around 7.5mb, i'll try to cheat and get it lower

**Comment by MrSunshyne** [comment]
closing. reopen if there are more suggestions
