### ISSUE TITLE
Page Code of Conduct

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#20]
Text needed for this page

**Comment by Humeira** [comment]
In previous version it was link to [MSCC Code of Conduct on meetup](https://www.meetup.com/MauritiusSoftwareCraftsmanshipCommunity/pages/19092247/Code_of_Conduct/ 
)
Do we put a dedicated page for this or simply direct to the above link?

**Comment by Jheengut** [comment]
The link has been updated to the https://www.mscc.mu/code-of-conduct/

**Comment by jochenkirstaetter** [comment]
Hi, yes, we have the general CoC on the MSCC blog as mentioned by Pritvi.

https://www.mscc.mu/code-of-conduct

The hyperlink in the footer should use that URL and we're done with this issue.

Cheers, JoKi

**Comment by Humeira** [comment]
Okay, I'm on it.

**Comment by MrSunshyne** [comment]
added the  link
