### ISSUE TITLE
Page Life at Devcon

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#23]
Text needed for this page

**Comment by jochenkirstaetter** [comment]
Hi @vchellen 
What's the idea behind this menu entry? Please elaborate...

Cheers, JoKi

**Comment by MrSunshyne** [comment]
Idea: Could be a gallery of the best photos(with caption) ?

**Comment by jochenkirstaetter** [comment]
Sounds good,
As we spoke last time... Writing could be `geeky` using the following: Li[f|v]e at DevCon

Perhaps it's too much - any comment?

Cheers, JoKi

**Comment by MrSunshyne** [comment]
This page has been merged with 'past-events' and is also the same target for the about page.

closing
