### ISSUE TITLE
Preserve scroll when coming back to session listing

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#30]
Steps to reproduce : 

1. Go to sessions listing
2. Choose Friday
3. Chose any session
4. Click the back button

Expected behaviour : 
Go back to Friday tab at same scroll position

Actual behaviour : 
Goes back to Thursday and resets scroll position.

hints:  `vue keep-alive`

**Comment by MrSunshyne** [comment]
Cedric told me you could help with this @Humeira

**Comment by YourFavouriteOreo** [comment]
@MrSunshyne  posted a pull request to handle this.

**Comment by MrSunshyne** [comment]
Tested and merged into dev! thanks!
