### ISSUE TITLE
Banners design + Page Press

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#34]
The press page has been added and styled.
see here : https://youthful-panini-25fb9a.netlify.com/#/press

There are three banner update required : 

- [ ] 720x200
- [ ] 970x90
- [ ] 409x280
- [x] Facebook Cover
- [x] Twitter Cover
- [x] Sticker

The page currently shows last year's banners.

**Comment by jochenkirstaetter** [comment]
Additionally, we would need banners for the header area on Twitter, Facebook, LinkedIn, and Google+.

What are the dimensions?

**Comment by MrSunshyne** [comment]
Facebook twitter and stickers updated on press page. I commented out the 3 others until they're ready.
