### ISSUE TITLE
Display Stats 

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#40]
Display the stats from VueX to the component

**Comment by cedpoilly** [comment]
@MrSunshyne done 😛
@all feel free to contribute: [spreadsheet](https://docs.google.com/spreadsheets/d/1IOjVVzveO5bSGpPY4CK3buyhUyb09o4U2wZ2nYp8ZpU/edit?usp=drivesdk)

**Comment by MrSunshyne** [comment]
meteoman added !
