### ISSUE TITLE
Display sponsors

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#41]
Display the sponsors from VueX to the component.

**Comment by MrSunshyne** [comment]
@cedpoilly the imageName/imageLink field is missing

**Comment by cedpoilly** [comment]
I've added the column, and added the sample sponsor images we currently have on the repo: [mcb](https://raw.githubusercontent.com/mscraftsman/devcon2019/dev/web/app/src/assets/sample-sponsors/mcb.svg) & [sdworks](https://raw.githubusercontent.com/mscraftsman/devcon2019/dev/web/app/src/assets/sample-sponsors/sdworx.svg).
Is there a branch I can use to test it?

**Comment by MrSunshyne** [comment]
@cedpoilly you can check here on the branch `f-dynamic-sponsors`

I added the listing, and the component only shows platinum for now. (the code isn't that clean yet).

The images(svg) don't show up. Weird. MIME type of svgs are text/plain in network panel

**Comment by cedpoilly** [comment]
Managed to get the MIME type to svg (adding "?sanitize=true" at the end the link) with no better results

**Comment by MrSunshyne** [comment]
added colors

**Comment by MrSunshyne** [comment]
done !
