### ISSUE TITLE
Loader for routes

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#50]
When clicking on link in staging/prod, it takes time to load the component and render it. 

This is mainly due to the fact that we are code-splitting at router level to make the initial load fast. 

Solutions to make this more bearable : 
- [ ] Loading animation on click (Menu + site anchors)
- [ ] Global unified loader for all things.
- [ ] Some Prefetching magic on the links

Suggestions and PR welcome !

**Comment by JulesMike** [comment]
- [x] Loading animation on click (Menu + site anchors)

Note: 
> - [ ] Global unified loader for all things.
Same loader can be used for other things like async tasks :smile: 
> - [ ] Some Prefetching magic on the links
Have not yet attempted any pre-fetching magic yet.

**Comment by MrSunshyne** [comment]
Nice use of the line at the top. Looks good, however @JulesMike seems when the user scrolls to the footer and uses the menu, the loader isn't visible anymore. In that case we might offset the loader to be fixed at the top of the page.

Possible Improvement if anyone wants to contrib.
When header-stripe is not in viewport, loader becomes positioned fixed at the top so that it's always visible.

**Comment by MrSunshyne** [comment]
@JulesMike How did you make the gif on Linux btw ?

**Comment by JulesMike** [comment]
@MrSunshyne 
> How did you make the gif on Linux btw ? I'm using `Gifrocket` on macOS

Using a chrome extension called `Chrome Capture`

> When header-stripe is not in viewport, loader becomes positioned fixed at the top so that it's always visible.

I created a new PR #56. Hope it suits well :smile: 

>Nice use of the line at the top.

Thank you :+1:
