### ISSUE TITLE
Page Past Events

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#53]
The past events page should show all the MSCC past events in a beautiful manner. 

Last year's page looked like this : 

![image](https://user-images.githubusercontent.com/1721611/50394186-56c79800-0775-11e9-92b3-5621c7437d6d.png)

A new design is most welcome, as well as the implementation. 

Ideas : timeline style? Zigzag style?

The content will be : DevCon2015, DevCon2016, DevCon2017, DevCon2018, DevCon2019, etc... see last years page.

**Comment by JordanBienvenue** [comment]
on it

**Comment by JordanBienvenue** [comment]
@MrSunshyne  i need permission to push please

**Comment by Humeira** [comment]
@JordanBienvenue send a PR

**Comment by kushul** [comment]
Already done. @MrSunshyne close the issue please
