### ISSUE TITLE
Variable Font

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#54]
Just an idea. Could be fun ! 

Remove dependency from all fonts and just only one variable font. 

The font "[Decovar](https://www.axis-praxis.org/specimens/decovar)" seems particularly interesting.

**Comment by MrSunshyne** [comment]
Decovar even has an "Inline" parameters we can use for our headings !

**Comment by MrSunshyne** [comment]
being tested over at the branch [`f-variable-font`](https://github.com/mscraftsman/devcon2019/tree/f-variable-font)

**Comment by Saamiyah** [comment]
Working on this enhancement.

**Comment by vchellen** [comment]
Just pulled the repo and check with my Designer.. A big NO GO for him as it spoils the whole look and feel of the website. May be next year when we have a wider range of supported Variable fonts.

**Comment by jochenkirstaetter** [comment]
Hi all!
Perhaps for a future edition of the website :)

Closing this issue for now.

Cheers, JoKi

**Comment by MrSunshyne** [comment]
@vchellen what do you mean by "when we have a wider range of supported Variable fonts." ?
