### ISSUE TITLE
Page: Press Material

### ISSUE THREAD

**Issue by jochenkirstaetter** [mscraftsman/devcon2019#66]
Is your feature request related to a problem? Please describe.
Like in previous years we should have a designated page with all kind of banner material that could be used for our campaign on social media and by partners to advertise and promote the conference.

It could also host an official press release in English (and French).

Describe the solution you'd like
Overview of images / banners with source snippet on how to embed each, and link to download for other purposes.

**Comment by MrSunshyne** [comment]
Hi @jochenkirstaetter, please remove the dummy description if it's not needed from the issue. 

The Press page has already been done here btw : https://youthful-panini-25fb9a.netlify.com/#/press

Is something else needed on that page?

**Comment by jochenkirstaetter** [comment]
Okidoki,
Let's keep it that way. Needs 2019 banners before we can deploy it. ;-)

**Comment by MrSunshyne** [comment]
Yes, all already referenced here #34 

Calling upon @vchellen to save the day 😇
