### ISSUE TITLE
HashTags

### ISSUE THREAD

**Issue by RealDotNetDave** [mscraftsman/devcon2019#72]
It would be useful to put the official conference hashtags at the top of the home page. Makes it easier for us to promote via Twitter, LinkedIn, etc.

**Comment by vchellen** [comment]
Yes it is on the initial design and will be added in the upcoming days

**Comment by MrSunshyne** [comment]
It appeared kinda crowded with the hashtag in the background. 
Can we put it in the slider instead @vchellen ?

Something like this

![image](https://user-images.githubusercontent.com/1721611/53402460-357c6580-39cb-11e9-85ba-bbd12140dc9f.png)

**Comment by vchellen** [comment]
Non it can't be in the slider.. I'll check with the designer to have something less crowded and make nashvin do it.. It will be easier than redoing psd and such.. they can just have a side by side test and see to it..

**Comment by MrSunshyne** [comment]
this is done ! closing
