### ISSUE TITLE
dotNetDave Guitar Performance

### ISSUE THREAD

**Issue by RealDotNetDave** [mscraftsman/devcon2019#73]
It would show how fun this conference is by putting my guitar performance from the end of the conference last year!

**Comment by MrSunshyne** [comment]
That would be cool! 

@RealDotNetDave @jochenkirstaetter @vchellen  do we have a video(preferably youtube link) of that?

**Comment by jochenkirstaetter** [comment]
Hi, I'll check the video material with David and on Facebook and am going to upload everything into the MSCC YouTube channel. URLs shall be available soon to embed them into the "Life at DevCon" area.

Cheers, JoKi
