### ISSUE TITLE
Homepage Components Front-end

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2019#8]
- [x] Top Bar
- [x] Header Stripe
- [x] Intro Slider
- [x] Five Years
- [x] DevCon Stats
- [x] Featured Speakers
- [x] Become Speaker
- [x] Sponsor Tile
- [x] Social Stripe
- [x] Footer

**Comment by MrSunshyne** [comment]
The components for the homepage follow these patterns

Homepage

# Top Bar

    component: top-bar
    create: touch top-bar.vue
    import: import TopBar from '@/components/homepage/top-bar.vue'
    name: TopBar
    tag: <TopBar />

# Header Stripe

    component: header-stripe
    create: touch header-stripe.vue
    import: import HeaderStripe from '@/components/homepage/header-stripe.vue'
    name: HeaderStripe
    tag: <HeaderStripe />

# Intro Slider

    component: intro-slider
    create: touch intro-slider.vue
    import: import IntroSlider from '@/components/homepage/intro-slider.vue'
    name: IntroSlider
    tag: <IntroSlider />

# Five Years

    component: five-years
    create: touch five-years.vue
    import: import FiveYears from '@/components/homepage/five-years.vue'
    name: FiveYears
    tag: <FiveYears />

# DevCon Stats

    component: devcon-stats
    create: touch devcon-stats.vue
    import: import DevconStats from '@/components/homepage/devcon-stats.vue'
    name: DevconStats
    tag: <DevconStats />

# Featured Speakers

    component: featured-speakers
    create: touch featured-speakers.vue
    import: import FeaturedSpeakers from '@/components/homepage/featured-speakers.vue'
    name: FeaturedSpeakers
    tag: <FeaturedSpeakers />

# Become Speaker

    component: become-speaker
    create: touch become-speaker.vue
    import: import BecomeSpeaker from '@/components/homepage/become-speaker.vue'
    name: BecomeSpeaker
    tag: <BecomeSpeaker />

# Sponsor Section

    component: sponsor-section
    create: touch sponsor-section.vue
    import: import SponsorSection from '@/components/homepage/sponsor-section.vue'
    name: SponsorSection
    tag: <SponsorSection />

# Social Stripe

    component: social-stripe
    create: touch social-stripe.vue
    import: import SocialStripe from '@/components/homepage/social-stripe.vue'
    name: SocialStripe
    tag: <SocialStripe />

# Footer Section

    component: footer-section
    create: touch footer-section.vue
    import: import FooterSection from '@/components/homepage/footer-section.vue'
    name: FooterSection
    tag: <FooterSection />

**Comment by arwinneil** [comment]
I'm having a go at the Social Stripe Component

![image](https://user-images.githubusercontent.com/20010676/49762974-ce60e600-fce4-11e8-90b8-e012584e9a13.png)

**Comment by MrSunshyne** [comment]
Featured speakers works in modern browsers. 
We need a fallback for disabled browsers.
