### ISSUE TITLE
DevCon2018-SponsorshipProposal gives 404

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2019#81]
this link 

[https://conference.mscc.mu/DevCon2018-SponsorshipProposal.pdf](https://conference.mscc.mu/DevCon2018-SponsorshipProposal.pdf)

returns 

```
404 Not Found
nginx
```

**Comment by jochenkirstaetter** [comment]
Hi,

Where is this link to be found?

Best regards, Jochen

**Comment by jochenkirstaetter** [comment]
Hi again,

Thanks for making us aware of the problem. I found it in the Extras section.
This has been corrected and will be deployed soon.

The correct link is: https://github.com/mscraftsman/devcon2019/raw/master/assets/DevCon2019-SponsorshipProposal.pdf

Thanks again and best regards, Jochen
